### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mikk369** [mikk369/newgarden#3]
- [ ] - Api endpoint todo for Kullapai
- [ ] - AddPosts - put the reversePosts function to backend
- [ ] - AddDocument - check if document FILE is added to documents folder
- [ ] - login/authentication
- [ ] proovi deploy teha ilma SSL (http)
